namespace Moneris
{
    using System;
    using System.Text;
    using System.Collections;

    public class TestCanadaMCPResCavvPurchaseCC
    {
        public static void Main(string[] args)
        {
            string store_id = "monca02932";
            string api_token = "CG8kYzGgzVU5z23irgMx";
            string data_key = "xRl9O4FgrZUYdGkmqHTqiEw97";
            string order_id = "Test" + DateTime.Now.ToString("yyyyMMddhhmmss");
            string amount = "1.00";
            string cust_id = "customer1"; //if sent will be submitted, otherwise cust_id from profile will be used
            string cavv = "AAABBJg0VhI0VniQEjRWAAAAAAA";
            string expdate = "1911";
            string processing_country_code = "CA";
            string ds_trans_id = "12345";
            bool status_check = false;

            CofInfo cof = new CofInfo();
            cof.SetPaymentIndicator("U");
            cof.SetPaymentInformation("2");
            cof.SetIssuerId("139X3130ASCXAS9");

            MCPResCavvPurchaseCC mcpResCavvPurchaseCC = new MCPResCavvPurchaseCC();
            mcpResCavvPurchaseCC.SetOrderId(order_id);
            mcpResCavvPurchaseCC.SetDataKey(data_key);
            mcpResCavvPurchaseCC.SetCustId(cust_id);
            mcpResCavvPurchaseCC.SetAmount(amount);
            mcpResCavvPurchaseCC.SetCavv(cavv);
            mcpResCavvPurchaseCC.SetExpDate(expdate); //mandatory for temp token only
            mcpResCavvPurchaseCC.SetCryptType("7");
            mcpResCavvPurchaseCC.SetThreeDSVersion("2"); //Mandatory for 3DS Version 2.0+
            mcpResCavvPurchaseCC.SetThreeDSServerTransId("e11d4985-8d25-40ed-99d6-c3803fe5e68f"); //Mandatory for 3DS Version 2.0+ - obtained from MpiCavvLookup or MpiThreeDSAuthentication
            mcpResCavvPurchaseCC.SetDsTransId(ds_trans_id); //Optional - to be used only if you are using 3rd party 3ds 2.0 service
            mcpResCavvPurchaseCC.SetCofInfo(cof);

            //MCP Fields
            mcpResCavvPurchaseCC.SetMCPVersion("1.0");
            mcpResCavvPurchaseCC.SetCardholderAmount("500");
            mcpResCavvPurchaseCC.SetCardholderCurrencyCode("840");
            mcpResCavvPurchaseCC.SetMCPRateToken("P1623439175449463");
            //mcpResCavvPurchaseCC.SetCmId("8nAK8712sGaAkls56"); //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant

            HttpsPostRequest mpgReq = new HttpsPostRequest();
            mpgReq.SetProcCountryCode(processing_country_code);
            mpgReq.SetTestMode(true); //false or comment out this line for production transactions
            mpgReq.SetStoreId(store_id);
            mpgReq.SetApiToken(api_token);
            mpgReq.SetTransaction(mcpResCavvPurchaseCC);
            mpgReq.SetStatusCheck(status_check);
            mpgReq.Send();

            try
            {
                Receipt receipt = mpgReq.GetReceipt();

                Console.WriteLine("DataKey = " + receipt.GetDataKey());
                Console.WriteLine("ReceiptId = " + receipt.GetReceiptId());
                Console.WriteLine("ReferenceNum = " + receipt.GetReferenceNum());
                Console.WriteLine("ResponseCode = " + receipt.GetResponseCode());
                Console.WriteLine("AuthCode = " + receipt.GetAuthCode());
                Console.WriteLine("Message = " + receipt.GetMessage());
                Console.WriteLine("TransDate = " + receipt.GetTransDate());
                Console.WriteLine("TransTime = " + receipt.GetTransTime());
                Console.WriteLine("TransType = " + receipt.GetTransType());
                Console.WriteLine("Complete = " + receipt.GetComplete());
                Console.WriteLine("TransAmount = " + receipt.GetTransAmount());
                Console.WriteLine("CardType = " + receipt.GetCardType());
                Console.WriteLine("TxnNumber = " + receipt.GetTxnNumber());
                Console.WriteLine("TimedOut = " + receipt.GetTimedOut());
                Console.WriteLine("ResSuccess = " + receipt.GetResSuccess());
                Console.WriteLine("PaymentType = " + receipt.GetPaymentType());
                Console.WriteLine("CavvResultCode = " + receipt.GetCavvResultCode());
                Console.WriteLine("IssuerId = " + receipt.GetIssuerId());
                Console.WriteLine("ThreeDSVersion = " + receipt.GetThreeDSVersion());

                //ResolveData
                Console.WriteLine("Cust ID = " + receipt.GetResDataCustId());
                Console.WriteLine("Phone = " + receipt.GetResDataPhone());
                Console.WriteLine("Email = " + receipt.GetResDataEmail());
                Console.WriteLine("Note = " + receipt.GetResDataNote());
                Console.WriteLine("Masked Pan = " + receipt.GetResDataMaskedPan());
                Console.WriteLine("Exp Date = " + receipt.GetResDataExpdate());
                Console.WriteLine("Crypt Type = " + receipt.GetResDataCryptType());
                Console.WriteLine("Avs Street Number = " + receipt.GetResDataAvsStreetNumber());
                Console.WriteLine("Avs Street Name = " + receipt.GetResDataAvsStreetName());
                Console.WriteLine("Avs Zipcode = " + receipt.GetResDataAvsZipcode());

                Console.WriteLine("MerchantSettlementAmount = " + receipt.GetMerchantSettlementAmount());
                Console.WriteLine("CardholderAmount = " + receipt.GetCardholderAmount());
                Console.WriteLine("CardholderCurrencyCode = " + receipt.GetCardholderCurrencyCode());
                Console.WriteLine("MCPRate = " + receipt.GetMCPRate());
                Console.WriteLine("MCPErrorStatusCode = " + receipt.GetMCPErrorStatusCode());
                Console.WriteLine("MCPErrorMessage = " + receipt.GetMCPErrorMessage());
                Console.WriteLine("HostId = " + receipt.GetHostId());
                Console.ReadLine();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
