namespace Moneris
{
    using System;
    using System.Collections.Generic;

    using System.Text;

    class TestCanadaPurchase
    {
		public static void Main(string[] args)
        {
            string store_id = "monca00597";
            string api_token = "uZIVXpqYgLn2epnt9HuH";
            string order_id = "Test" + DateTime.Now.ToString("yyyyMMddhhmmss");
            string amount = "21.00";
            string pan = "5214150084033640";
            string expdate = "2806"; //YYMM
            string crypt = "7";
            string processing_country_code = "CA";
            bool status_check = false;

			//CofInfo cof = new CofInfo();
			//cof.SetPaymentIndicator("U");
		//	cof.SetPaymentInformation("2");
			//cof.SetIssuerId("168451306048014");
			

            Purchase purchase = new Purchase();
            purchase.SetOrderId(order_id);
            purchase.SetAmount(amount);
            purchase.SetPan(pan);
            purchase.SetExpDate(expdate);
            purchase.SetCryptType(crypt);
            purchase.SetDynamicDescriptor("2134565");
			//purchase.SetWalletIndicator(""); //Refer to documentation for details
			//purchase.SetCofInfo(cof);

            // Optoinal - Installment Info
            // InstallmentInfo installmentInfo = new InstallmentInfo();
            // installmentInfo.SetPlanId("ae859ef1-eb91-b708-8b80-1dd481746401");
            // installmentInfo.SetPlanIdRef("0000000065");
            // installmentInfo.SetTacVersion("2");
            // purchase.SetInstallmentInfo(installmentInfo);

		    // TrId and TokenCryptogram are optional, refer documentation for more details.
            purchase.SetTrId("50189815682");
		    purchase.SetTokenCryptogram("APmbM/411e0uAAH+s6xMAAADFA==");
		    
		    SurchargeInfo surchargeInfo = new SurchargeInfo();
		    surchargeInfo.SetSurchargeAmount("1.00");
		    purchase.SetSurchargeInfo(surchargeInfo);
            //purchase.SetTrId("50189815682");
		    purchase.SetTokenCryptogram("MNbkHS4AAAINABNaBPIXAAADFAA=");
		   
		   PBBInfo pbbInfo= new PBBInfo();
		   String consentId="a441236b-178f-4e5b-bd2d-0fcc5ec7d87e";
		   //String cryptogram="eyJraWQiOiJpZGlyZWN0LXRva2VuLWp3cy0wMDEiLCJhbGciOiJFUzI1NiJ9..0I37qRcPh0lzhTupEwGgkqE_6PD6Nv6UOe37lUlStg0oH6ELp67BLHg8T8HzEwMWxVXk8qvISYvCu3XwNw_ADg";
		  // String cryptogramExpiry= "2024-08-28T17:54:48.000Z";
		   String paymentMethod ="MASTERCARD_CREDIT";
		 //  String channel="DESKTOP_WEB";
		   pbbInfo.setConsentId(consentId);
		//   pbbInfo.setCryptogram(cryptogram);
		//   pbbInfo.setCryptogramExpiry(cryptogramExpiry);
		   pbbInfo.setPaymentMethod(paymentMethod);
		//   pbbInfo.setChannel(channel);
		   purchase.setPbbInfo(pbbInfo);

			//purchase.SetCmId("8nAK8712sGaAkls56"); //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant

            HttpsPostRequest mpgReq = new HttpsPostRequest();
            mpgReq.SetProcCountryCode(processing_country_code);
            mpgReq.SetTestMode(true); //false or comment out this line for production transactions
            mpgReq.SetStoreId(store_id);
            mpgReq.SetApiToken(api_token);
            mpgReq.SetTransaction(purchase);
            mpgReq.SetStatusCheck(status_check);
            Console.WriteLine(mpgReq.toXML());
            mpgReq.Send();

            try
            {
                Receipt receipt = mpgReq.GetReceipt();

                Console.WriteLine("CardType = " + receipt.GetCardType());
                Console.WriteLine("TransAmount = " + receipt.GetTransAmount());
                Console.WriteLine("TxnNumber = " + receipt.GetTxnNumber());
                Console.WriteLine("ReceiptId = " + receipt.GetReceiptId());
                Console.WriteLine("TransType = " + receipt.GetTransType());
                Console.WriteLine("ReferenceNum = " + receipt.GetReferenceNum());
                Console.WriteLine("ResponseCode = " + receipt.GetResponseCode());
                Console.WriteLine("ISO = " + receipt.GetISO());
                Console.WriteLine("BankTotals = " + receipt.GetBankTotals());
                Console.WriteLine("Message = " + receipt.GetMessage());
                Console.WriteLine("AuthCode = " + receipt.GetAuthCode());
                Console.WriteLine("Complete = " + receipt.GetComplete());
                Console.WriteLine("TransDate = " + receipt.GetTransDate());
                Console.WriteLine("TransTime = " + receipt.GetTransTime());
                Console.WriteLine("Ticket = " + receipt.GetTicket());
                Console.WriteLine("TimedOut = " + receipt.GetTimedOut());
                Console.WriteLine("IsVisaDebit = " + receipt.GetIsVisaDebit());
                Console.WriteLine("HostId = " + receipt.GetHostId());
                Console.WriteLine("IssuerId = " + receipt.GetIssuerId());
                Console.WriteLine("SourcePanLast4 = " + receipt.GetSourcePanLast4());
                Console.WriteLine("Advice Code = " + receipt.GetAdviceCode());
                Console.WriteLine("PBBLifeCycleTraceId = " + receipt.GetPBBLifeCycleTraceId());

                // InstallmentResults installmentResults = receipt.GetInstallmentResults();

                // Console.WriteLine("\nPlanId = " + installmentResults.GetPlanId() +"\n");
                // Console.WriteLine("PlanIDRef = " + installmentResults.GetPlanIDRef());
                // Console.WriteLine("TacVersion = " + installmentResults.GetTacVersion());
                // Console.WriteLine("PlanAcceptanceId = " + installmentResults.GetPlanAcceptanceId());
                // Console.WriteLine("PlanStatus = " + installmentResults.GetPlanStatus()); 
                // Console.WriteLine("PlanResponse = " + installmentResults.GetPlanResponse());

                Console.ReadLine();

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
